package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// QuickKnowledgeBuilder builds knowledge base quickly
type QuickKnowledgeBuilder struct {
	sourceDir string
	targetDir string
	startTime time.Time
}

// NewQuickKnowledgeBuilder creates new builder
func NewQuickKnowledgeBuilder(sourceDir, targetDir string) *QuickKnowledgeBuilder {
	return &QuickKnowledgeBuilder{
		sourceDir: sourceDir,
		targetDir: targetDir,
		startTime: time.Now(),
	}
}

// Build builds knowledge base
func (qkb *QuickKnowledgeBuilder) Build() error {
	log.Println("=== 🚀 QUICK KNOWLEDGE BASE BUILD ===")

	// Create directories
	if err := qkb.createDirs(); err != nil {
		return fmt.Errorf("create dirs: %w", err)
	}

	// Copy important files
	if err := qkb.copyImportantFiles(); err != nil {
		return fmt.Errorf("copy files: %w", err)
	}

	// Create index
	if err := qkb.createIndex(); err != nil {
		return fmt.Errorf("create index: %w", err)
	}

	// Summary
	qkb.printSummary()

	return nil
}

// createDirs creates directories
func (qkb *QuickKnowledgeBuilder) createDirs() error {
	dirs := []string{
		"content/skills",
		"content/agents",
		"content/rules",
		"content/workflows",
		"apps-docs",
		"packages",
		"docs",
	}

	for _, dir := range dirs {
		fullPath := filepath.Join(qkb.targetDir, dir)
		if err := os.MkdirAll(fullPath, 0755); err != nil {
			return fmt.Errorf("create dir %s: %w", fullPath, err)
		}
	}

	log.Println("✅ Directories created")
	return nil
}

// copyImportantFiles copies important files
func (qkb *QuickKnowledgeBuilder) copyImportantFiles() error {
	log.Println("📁 Copying important files...")

	// Important files to copy
	importantFiles := []struct {
		source string
		target string
	}{
		{"AGENTS.md", "docs/AGENTS.md"},
		{"README.md", "docs/README.md"},
		{"apps-docs/00-index/INDEX.md", "apps-docs/INDEX.md"},
		{"apps-docs/03-operations/INDEX.md", "apps-docs/OPERATIONS.md"},
		{"apps-docs/01-architecture/INDEX.md", "apps-docs/ARCHITECTURE.md"},
		{"Ti-learning-lab/README.md", "content/skills/TI_LEARNING_LAB.md"},
		{"Ti-learning-lab/WORKFLOW.md", "content/workflows/TI_WORKFLOW.md"},
		{"Ti-learning-lab/MANIFEST.md", "content/rules/TI_MANIFEST.md"},
		{"apps/ticrew/README.md", "content/agents/TICREW.md"},
		{"apps/router/README.md", "content/agents/ROUTER.md"},
	}

	copied := 0
	for _, file := range importantFiles {
		sourcePath := filepath.Join(qkb.sourceDir, file.source)
		targetPath := filepath.Join(qkb.targetDir, file.target)

		if _, err := os.Stat(sourcePath); err == nil {
			if err := qkb.copyFile(sourcePath, targetPath); err == nil {
				copied++
				log.Printf("✅ Copied: %s", file.source)
			} else {
				log.Printf("❌ Failed to copy: %s", file.source)
			}
		} else {
			log.Printf("⚠️  Not found: %s", file.source)
		}
	}

	log.Printf("✅ Copied %d important files", copied)
	return nil
}

// copyFile copies a file
func (qkb *QuickKnowledgeBuilder) copyFile(src, dst string) error {
	// Create target directory
	if err := os.MkdirAll(filepath.Dir(dst), 0755); err != nil {
		return err
	}

	// Read source
	content, err := os.ReadFile(src)
	if err != nil {
		return err
	}

	// Write target
	return os.WriteFile(dst, content, 0644)
}

// createIndex creates knowledge index
func (qkb *QuickKnowledgeBuilder) createIndex() error {
	log.Println("📋 Creating knowledge index...")

	indexPath := filepath.Join(qkb.targetDir, "KNOWLEDGE_INDEX.md")

	content := fmt.Sprintf(`# Ti Ecosystem Knowledge Base

**Generated**: %s
**Build Time**: %s
**Total Files**: %d

## 📚 Categories

### 📖 Documentation
- [AGENTS.md](docs/AGENTS.md) - Agent integration guide
- [README.md](docs/README.md) - Project overview

### 🏗️ Apps Documentation  
- [INDEX.md](apps-docs/INDEX.md) - Master documentation index
- [OPERATIONS.md](apps-docs/OPERATIONS.md) - Operations guide
- [ARCHITECTURE.md](apps-docs/ARCHITECTURE.md) - Architecture documentation

### 💼 Skills & Learning
- [TI_LEARNING_LAB.md](content/skills/TI_LEARNING_LAB.md) - Learning lab overview

### 🤖 Agents
- [TICREW.md](content/agents/TICREW.md) - TiCrew agent documentation
- [ROUTER.md](content/agents/ROUTER.md) - Router agent documentation

### 🔄 Workflows
- [TI_WORKFLOW.md](content/workflows/TI_WORKFLOW.md) - Ti workflow guide

### 📋 Rules & Configs
- [TI_MANIFEST.md](content/rules/TI_MANIFEST.md) - Ti project manifest

## 🔍 Search Tips

This knowledge base contains essential Ti ecosystem documentation. Use semantic search to find:
- Agent configurations and capabilities
- Architecture patterns and best practices  
- Workflow processes and automation
- Learning resources and skill development
- Project rules and configurations

## 📊 Statistics

- **Build Method**: Quick Essential Files
- **Focus**: Core documentation and configurations
- **Update Frequency**: Manual updates recommended
- **Search**: Use Ti Brain RAG system for intelligent search

---
*Generated by Ti Knowledge Base Builder*
`, time.Now().Format("2006-01-02 15:04:05"), time.Since(qkb.startTime), qkb.countFiles())

	return os.WriteFile(indexPath, []byte(content), 0644)
}

// countFiles counts files in knowledge base
func (qkb *QuickKnowledgeBuilder) countFiles() int {
	count := 0

	filepath.Walk(qkb.targetDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}

		if strings.HasSuffix(strings.ToLower(path), ".md") {
			count++
		}
		return nil
	})

	return count
}

// printSummary prints build summary
func (qkb *QuickKnowledgeBuilder) printSummary() {
	log.Println("=== 📊 BUILD SUMMARY ===")
	log.Printf("Build Time: %s", time.Since(qkb.startTime))
	log.Printf("Target: %s", qkb.targetDir)
	log.Printf("Files: %d", qkb.countFiles())
	log.Println("🎉 Quick knowledge base completed!")
}
