package translate

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

func Convert(root string, findings []Finding, name string) (*Pack, LockFile, error) {
	if root == "" {
		root = "."
	}
	if name == "" {
		name = "translated-pack"
	}
	p := &Pack{
		APIVersion: "ti.dev/v1",
		Kind:       "TiPack",
		Metadata: Metadata{
			Name:        slug(name),
			Description: "Generated by Ti Translate Engine",
			GeneratedAt: time.Now().UTC(),
			Source:      "translate",
			Version:     "v0.7.0",
		},
	}
	lock := LockFile{GeneratedAt: time.Now().UTC(), Version: "v0.7.0"}
	for _, f := range findings {
		full := filepath.Join(root, filepath.FromSlash(f.Path))
		data, err := os.ReadFile(full)
		if err != nil {
			p.Risks = append(p.Risks, Risk{Level: "low", Reason: "could not read source: " + err.Error(), Action: "check file permissions", Source: SourceRef{Format: f.Format, Path: f.Path, Kind: f.Kind}})
			continue
		}
		convertOne(p, f, string(data))
		hash, _ := SHA256File(full)
		lock.Imports = append(lock.Imports, LockEntry{SourcePath: f.Path, Format: f.Format, Kind: f.Kind, ImportedAs: importedAs(f), SHA256: hash, ImportedAt: time.Now().UTC()})
	}
	finalizePack(p)
	return p, lock, nil
}

func convertOne(p *Pack, f Finding, raw string) {
	fm, body := SplitFrontMatter(raw)
	src := SourceRef{Format: f.Format, Path: f.Path, Kind: f.Kind}
	id := uniqueID(f.Format + "-" + f.Kind + "-" + f.Name)
	desc := firstNonEmpty(fm["description"], fm["summary"], fm["name"], fm["title"])
	tools := ParseTools(firstNonEmpty(fm["allowed-tools"], fm["tools"], fm["tool"], fm["permissions"]), f.Format)
	body = NormalizePromptVariables(body, f.Format)
	sandbox := RequiresSandbox(body, tools)
	p.Risks = append(p.Risks, DetectRisks(body, tools, src)...)
	for _, note := range f.Risks {
		p.Risks = append(p.Risks, Risk{Level: "medium", Reason: note, Action: "review before enabling", Source: src})
	}

	switch f.Kind {
	case "instruction", "rule":
		p.Instructions = append(p.Instructions, Instruction{ID: id, Name: f.Name, Scope: inferScope(f), Globs: ParseGlobs(fm, f), Content: strings.TrimSpace(body), Meta: fm, Source: src})
	case "command":
		p.Commands = append(p.Commands, Command{ID: id, Name: f.Name, Description: desc, Prompt: strings.TrimSpace(body), Args: ParseArgs(fm, body), Tools: tools, Metadata: fm, Sandbox: sandbox, Source: src})
	case "agent":
		p.Agents = append(p.Agents, Agent{ID: id, Name: f.Name, Description: desc, Prompt: strings.TrimSpace(body), Model: firstNonEmpty(fm["model"], fm["model-id"]), Tools: tools, Mode: firstNonEmpty(fm["mode"], fm["type"]), Sandbox: sandbox, Metadata: fm, Source: src})
	case "skill":
		p.Skills = append(p.Skills, Skill{ID: id, Name: f.Name, Description: desc, Content: strings.TrimSpace(body), Tags: ParseTags(fm), Metadata: fm, Source: src})
	case "settings", "hooks":
		parseSettingsIntoPack(p, src, raw)
	case "mcp_server_config":
		p.MCPServers = append(p.MCPServers, ParseMCPServers(raw, src)...)
	case "config":
		parseConfigIntoPack(p, src, raw)
	case "plugin":
		p.Plugins = append(p.Plugins, Plugin{Name: f.Name, Runtime: pluginRuntime(f.Path), Command: f.Path, Sandbox: true, Description: desc, Source: src})
		p.Risks = append(p.Risks, Risk{Level: "high", Reason: "external plugin code detected", Action: "run only through plugin bridge with sandbox and audit log", Source: src})
	case "workflow":
		p.Workflows = append(p.Workflows, Workflow{ID: id, Name: f.Name, Description: desc, Steps: inferWorkflowSteps(body), Source: src})
	default:
		p.Instructions = append(p.Instructions, Instruction{ID: id, Name: f.Name, Scope: inferScope(f), Content: strings.TrimSpace(body), Meta: fm, Source: src})
	}
}

func finalizePack(p *Pack) {
	p.Risks = dedupeRisks(p.Risks)
	p.Conflicts = append(p.Conflicts, DetectConflicts(p.Instructions)...)
	sort.Slice(p.Instructions, func(i, j int) bool { return p.Instructions[i].ID < p.Instructions[j].ID })
	sort.Slice(p.Commands, func(i, j int) bool { return p.Commands[i].ID < p.Commands[j].ID })
	sort.Slice(p.Agents, func(i, j int) bool { return p.Agents[i].ID < p.Agents[j].ID })
	sort.Slice(p.Skills, func(i, j int) bool { return p.Skills[i].ID < p.Skills[j].ID })
	sort.Slice(p.MCPServers, func(i, j int) bool { return p.MCPServers[i].Name < p.MCPServers[j].Name })
	sort.Slice(p.Providers, func(i, j int) bool { return p.Providers[i].Name < p.Providers[j].Name })
}

func SplitFrontMatter(s string) (FrontMatter, string) {
	fm := FrontMatter{}
	trim := strings.TrimPrefix(s, "\ufeff")
	if !strings.HasPrefix(trim, "---\n") && !strings.HasPrefix(trim, "---\r\n") {
		return fm, s
	}
	scanner := bufio.NewScanner(strings.NewReader(trim))
	lineNo := 0
	var fmLines []string
	var bodyLines []string
	inFM := false
	closed := false
	for scanner.Scan() {
		line := scanner.Text()
		if lineNo == 0 && strings.TrimSpace(line) == "---" {
			inFM = true
			lineNo++
			continue
		}
		if inFM && strings.TrimSpace(line) == "---" {
			inFM = false
			closed = true
			lineNo++
			continue
		}
		if inFM {
			fmLines = append(fmLines, line)
		} else {
			bodyLines = append(bodyLines, line)
		}
		lineNo++
	}
	if !closed {
		return FrontMatter{}, s
	}
	parseLooseYAMLMap(fm, fmLines)
	return fm, strings.Join(bodyLines, "\n")
}

func parseLooseYAMLMap(fm FrontMatter, lines []string) {
	var current string
	for _, line := range lines {
		trim := strings.TrimSpace(line)
		if trim == "" || strings.HasPrefix(trim, "#") {
			continue
		}
		if strings.HasPrefix(trim, "-") && current != "" {
			val := strings.TrimSpace(strings.TrimPrefix(trim, "-"))
			val = strings.Trim(val, `"'`)
			if fm[current] == "" {
				fm[current] = val
			} else {
				fm[current] += "," + val
			}
			continue
		}
		parts := strings.SplitN(line, ":", 2)
		if len(parts) != 2 {
			continue
		}
		key := strings.TrimSpace(strings.ToLower(parts[0]))
		val := strings.TrimSpace(parts[1])
		val = strings.Trim(val, `"'`)
		current = key
		fm[key] = val
	}
}

func ParseTools(raw string, format string) []string {
	if raw == "" {
		return nil
	}
	raw = strings.Trim(raw, "[]")
	repl := strings.NewReplacer("\"", "", "'", "", "\n", ",", ";", ",", "|", ",")
	raw = repl.Replace(raw)
	parts := strings.Split(raw, ",")
	var out []string
	seen := map[string]bool{}
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		tool := normalizeTool(part)
		if tool == "" {
			continue
		}
		if !seen[tool] {
			seen[tool] = true
			out = append(out, tool)
		}
	}
	return out
}

func ParseArgs(fm FrontMatter, body string) []Arg {
	hint := firstNonEmpty(fm["argument-hint"], fm["args"], fm["arguments"], fm["params"], fm["parameters"])
	seen := map[string]bool{}
	var out []Arg
	add := func(name string, required bool) {
		name = strings.Trim(name, "<>[]{}()$,:`\"'")
		name = strings.TrimPrefix(name, "--")
		name = slug(name)
		if name == "" || seen[name] {
			return
		}
		seen[name] = true
		out = append(out, Arg{Name: name, Required: required})
	}
	if hint != "" {
		hint = strings.Trim(hint, "[]")
		hint = strings.NewReplacer(",", " ", "|", " ").Replace(hint)
		for _, field := range strings.Fields(hint) {
			add(field, strings.HasPrefix(field, "<") || strings.Contains(field, "required"))
		}
	}
	if strings.Contains(body, "{{args.arguments}}") || strings.Contains(body, "$ARGUMENTS") {
		add("arguments", false)
	}
	for _, match := range regexp.MustCompile(`\{\{\s*args\.([a-zA-Z0-9_-]+)\s*\}\}`).FindAllStringSubmatch(body, -1) {
		add(match[1], false)
	}
	return out
}

func ParseGlobs(fm FrontMatter, f Finding) []string {
	raw := firstNonEmpty(fm["globs"], fm["glob"], fm["files"], fm["applies-to"], fm["applies_to"])
	if raw == "" {
		if strings.Contains(f.Path, "/rules/") {
			return []string{"**/*"}
		}
		return nil
	}
	return splitList(raw)
}

func ParseTags(fm FrontMatter) []string {
	return splitList(firstNonEmpty(fm["tags"], fm["tag"], fm["categories"]))
}

func NormalizePromptVariables(body string, format string) string {
	body = strings.ReplaceAll(body, "$ARGUMENTS", "{{args.arguments}}")
	body = strings.ReplaceAll(body, "${ARGUMENTS}", "{{args.arguments}}")
	body = regexp.MustCompile(`\$([A-Z][A-Z0-9_]+)`).ReplaceAllStringFunc(body, func(s string) string {
		name := strings.ToLower(strings.TrimPrefix(s, "$"))
		if name == "arguments" {
			return "{{args.arguments}}"
		}
		return "{{env." + name + "}}"
	})
	return body
}

func DetectRisks(body string, tools []string, src SourceRef) []Risk {
	var risks []Risk
	lower := strings.ToLower(body)
	for _, tool := range tools {
		switch tool {
		case "bash", "shell", "write_file", "edit_file", "delete", "webfetch", "network":
			risks = append(risks, Risk{Level: "medium", Reason: "tool permission may modify files, run commands, or access network: " + tool, Action: "require sandbox and permission approval", Source: src})
		}
	}
	patterns := map[string]string{
		"rm -rf":       "destructive delete command",
		"curl ":        "network download command",
		"wget ":        "network download command",
		"| bash":       "pipe-to-shell pattern",
		"npm install":  "dependency installation command",
		"pnpm install": "dependency installation command",
		"pip install":  "dependency installation command",
		"git push":     "remote write command",
		"chmod 777":    "broad permission change",
		"sudo ":        "privilege escalation command",
		"delete":       "deletion instruction",
		"remove files": "file removal instruction",
	}
	for pat, reason := range patterns {
		if strings.Contains(lower, pat) {
			level := "medium"
			if pat == "rm -rf" || pat == "| bash" || pat == "sudo " {
				level = "high"
			}
			risks = append(risks, Risk{Level: level, Reason: reason + ": " + pat, Action: "review before enabling; run through Ti sandbox", Source: src})
		}
	}
	return dedupeRisks(risks)
}

func RequiresSandbox(body string, tools []string) bool {
	return len(DetectRisks(body, tools, SourceRef{})) > 0
}

func ParseMCPServers(raw string, src SourceRef) []MCPServer {
	clean := stripJSONComments(raw)
	var root map[string]any
	if err := json.Unmarshal([]byte(clean), &root); err != nil {
		return []MCPServer{{Name: "mcp", Sandbox: true, Source: src}}
	}
	servers, ok := anyMap(root["mcpServers"])
	if !ok {
		servers, ok = anyMap(root["servers"])
	}
	if !ok {
		return nil
	}
	var out []MCPServer
	for name, value := range servers {
		m := MCPServer{Name: slug(name), Sandbox: true, Source: src}
		if cfg, ok := value.(map[string]any); ok {
			m.Command = strAny(cfg["command"])
			m.URL = strAny(cfg["url"])
			m.Args = anyStringSlice(cfg["args"])
			m.Env = anyStringMap(cfg["env"])
		}
		out = append(out, m)
	}
	return out
}

func parseSettingsIntoPack(p *Pack, src SourceRef, raw string) {
	clean := stripJSONComments(raw)
	var root map[string]any
	if err := json.Unmarshal([]byte(clean), &root); err != nil {
		p.Risks = append(p.Risks, Risk{Level: "medium", Reason: "could not parse settings JSON; preserved as manual review item", Action: "review original settings", Source: src})
		return
	}
	if v, ok := root["permissions"]; ok {
		p.Permissions = append(p.Permissions, parsePermissions(v, src)...)
	}
	for _, key := range []string{"hooks", "commands", "events"} {
		if v, ok := root[key]; ok {
			p.Hooks = append(p.Hooks, parseHooks(v, src)...)
		}
	}
	if len(p.Hooks) > 0 {
		p.Risks = append(p.Risks, Risk{Level: "high", Reason: "settings file defines hooks or event commands", Action: "manual review required; keep sandbox enabled", Source: src})
	}
}

func parseConfigIntoPack(p *Pack, src SourceRef, raw string) {
	clean := stripJSONComments(raw)
	var root map[string]any
	if err := json.Unmarshal([]byte(clean), &root); err == nil {
		p.MCPServers = append(p.MCPServers, ParseMCPServers(clean, src)...)
		p.Providers = append(p.Providers, parseProviders(root, src)...)
		p.Hooks = append(p.Hooks, parseHooks(root["hooks"], src)...)
		p.Permissions = append(p.Permissions, parsePermissions(root["permissions"], src)...)
		return
	}
	// YAML-ish configs are preserved as instructions/workflows because Go stdlib has no YAML parser.
	p.Workflows = append(p.Workflows, Workflow{ID: uniqueID(src.Format + "-config-" + filepath.Base(src.Path)), Name: slug(filepath.Base(src.Path)), Description: "YAML-like config imported as review workflow", Steps: inferWorkflowSteps(raw), Source: src})
	p.Risks = append(p.Risks, Risk{Level: "medium", Reason: "YAML-like config imported conservatively", Action: "review generated workflow before enabling", Source: src})
}

func parseProviders(root map[string]any, src SourceRef) []ProviderRef {
	var out []ProviderRef
	for _, key := range []string{"provider", "providers", "compatible_providers", "models"} {
		v, ok := root[key]
		if !ok {
			continue
		}
		switch x := v.(type) {
		case []any:
			for i, item := range x {
				if m, ok := item.(map[string]any); ok {
					out = append(out, providerRefFromMap(fmt.Sprintf("provider-%d", i+1), m, src))
				}
			}
		case map[string]any:
			for name, item := range x {
				if m, ok := item.(map[string]any); ok {
					out = append(out, providerRefFromMap(name, m, src))
				}
			}
			if p := providerRefFromMap("provider", x, src); p.BaseURL != "" {
				out = append(out, p)
			}
		}
	}
	return dedupeProviders(out)
}

func providerRefFromMap(name string, m map[string]any, src SourceRef) ProviderRef {
	p := ProviderRef{Name: slug(firstNonEmpty(strMap(m, "name"), strMap(m, "id"), name)), Type: "openai_compatible", Source: src}
	p.BaseURL = strings.TrimRight(firstNonEmpty(strMap(m, "base_url"), strMap(m, "baseURL"), strMap(m, "baseUrl"), strMap(m, "api_base"), strMap(m, "url"), strMap(m, "endpoint")), "/")
	p.APIKeyEnv = firstNonEmpty(strMap(m, "api_key_env"), strMap(m, "apiKeyEnv"), strMap(m, "env"), strMap(m, "keyEnv"))
	if p.APIKeyEnv == "" {
		for _, k := range []string{"apiKey", "api_key", "key"} {
			if env := trimEnvRef(strMap(m, k)); env != strMap(m, k) || strings.HasPrefix(strMap(m, k), "$") {
				p.APIKeyEnv = env
			}
		}
	}
	p.DefaultModel = firstNonEmpty(strMap(m, "default_model"), strMap(m, "defaultModel"), strMap(m, "model"))
	p.Models = anyStringSlice(firstAnyMap(m, "models", "model_ids", "modelIDs"))
	if len(p.Models) == 0 && p.DefaultModel != "" {
		p.Models = []string{p.DefaultModel}
	}
	p.Headers = anyStringMap(firstAnyMap(m, "headers", "custom_headers", "customHeaders"))
	return p
}

func parsePermissions(v any, src SourceRef) []Permission {
	var out []Permission
	add := func(subject, action, mode string, paths []string) {
		if subject == "" {
			subject = "tool"
		}
		if action == "" {
			action = "*"
		}
		if mode == "" {
			mode = "ask"
		}
		out = append(out, Permission{Subject: slug(subject), Action: slug(action), Mode: slug(mode), Paths: paths, Source: src})
	}
	switch x := v.(type) {
	case map[string]any:
		for k, val := range x {
			switch y := val.(type) {
			case string:
				add(k, "*", y, nil)
			case []any:
				add("tool", k, "allow", anyStringSlice(y))
			case map[string]any:
				add(k, strAny(y["action"]), strAny(y["mode"]), anyStringSlice(y["paths"]))
			}
		}
	case []any:
		for _, item := range x {
			if m, ok := item.(map[string]any); ok {
				add(strAny(m["subject"]), strAny(m["action"]), strAny(m["mode"]), anyStringSlice(m["paths"]))
			}
		}
	}
	return out
}

func parseHooks(v any, src SourceRef) []Hook {
	var out []Hook
	add := func(event, run, matcher string) {
		if strings.TrimSpace(run) == "" {
			return
		}
		out = append(out, Hook{Event: firstNonEmpty(event, "imported"), Run: run, Matcher: matcher, Sandbox: true, Source: src})
	}
	switch x := v.(type) {
	case map[string]any:
		for event, val := range x {
			switch y := val.(type) {
			case string:
				add(event, y, "")
			case []any:
				for _, item := range y {
					if s, ok := item.(string); ok {
						add(event, s, "")
					} else if m, ok := item.(map[string]any); ok {
						add(event, firstNonEmpty(strAny(m["command"]), strAny(m["run"]), strAny(m["cmd"])), strAny(m["matcher"]))
					}
				}
			case map[string]any:
				add(event, firstNonEmpty(strAny(y["command"]), strAny(y["run"]), strAny(y["cmd"])), strAny(y["matcher"]))
			}
		}
	case []any:
		for _, item := range x {
			if m, ok := item.(map[string]any); ok {
				add(strAny(m["event"]), firstNonEmpty(strAny(m["command"]), strAny(m["run"]), strAny(m["cmd"])), strAny(m["matcher"]))
			}
		}
	}
	return out
}

func inferWorkflowSteps(body string) []WorkflowStep {
	var steps []WorkflowStep
	for _, line := range strings.Split(body, "\n") {
		trim := strings.TrimSpace(strings.TrimPrefix(line, "-"))
		low := strings.ToLower(trim)
		if strings.HasPrefix(low, "run:") || strings.HasPrefix(low, "command:") || strings.HasPrefix(low, "cmd:") {
			parts := strings.SplitN(trim, ":", 2)
			if len(parts) == 2 {
				run := strings.TrimSpace(parts[1])
				steps = append(steps, WorkflowStep{Run: run, Sandbox: RequiresSandbox(run, nil)})
			}
		}
	}
	if len(steps) == 0 && strings.TrimSpace(body) != "" {
		steps = append(steps, WorkflowStep{Name: "review", Run: "review original workflow content", Sandbox: true})
	}
	return steps
}

func DetectConflicts(instructions []Instruction) []Conflict {
	checks := map[string][]string{
		"package-manager": {"npm", "pnpm", "yarn", "bun"},
		"go-version":      {"go 1.20", "go 1.21", "go 1.22", "go 1.23", "go 1.24", "go 1.25", "go 1.26"},
	}
	var conflicts []Conflict
	for topic, tokens := range checks {
		seen := map[string][]SourceRef{}
		for _, ins := range instructions {
			low := strings.ToLower(ins.Content)
			for _, token := range tokens {
				if strings.Contains(low, token) {
					seen[token] = append(seen[token], ins.Source)
				}
			}
		}
		if len(seen) > 1 {
			var srcs []SourceRef
			var found []string
			for token, ss := range seen {
				found = append(found, token)
				srcs = append(srcs, ss...)
			}
			sort.Strings(found)
			conflicts = append(conflicts, Conflict{ID: uniqueID(topic + "-conflict"), Level: "warning", Topic: topic, Message: "multiple possible values detected: " + strings.Join(found, ", "), Sources: srcs})
		}
	}
	return conflicts
}

var nonSlug = regexp.MustCompile(`[^a-zA-Z0-9_.-]+`)

func slug(s string) string {
	s = strings.TrimSpace(strings.ToLower(s))
	s = strings.TrimSuffix(s, filepath.Ext(s))
	s = nonSlug.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-_.")
	if s == "" {
		return "item"
	}
	return s
}

func normalizeTool(s string) string {
	s = slug(s)
	s = strings.TrimPrefix(s, "mcp__")
	s = strings.ReplaceAll(s, "__", "_")
	switch s {
	case "bash", "shell", "terminal", "run-command", "run_command":
		return "bash"
	case "read", "readfile", "read_file", "view":
		return "read_file"
	case "write", "writefile", "write_file", "create":
		return "write_file"
	case "edit", "multiedit", "multi_edit", "editfile", "edit_file":
		return "edit_file"
	case "grep", "search", "ripgrep":
		return "grep"
	case "glob", "ls":
		return "glob"
	case "webfetch", "web-fetch", "fetch":
		return "webfetch"
	case "websearch", "web-search":
		return "websearch"
	}
	return s
}

func inferScope(f Finding) string {
	if f.Format == FormatCursor || f.Format == FormatWindsurf {
		return "scoped"
	}
	if strings.Contains(f.Path, "/") {
		return "scoped"
	}
	return "project"
}

func importedAs(f Finding) string { return f.Kind + ":" + f.Name }
func uniqueID(s string) string    { return slug(s) }

func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if strings.TrimSpace(v) != "" {
			return strings.TrimSpace(v)
		}
	}
	return ""
}

func dedupeRisks(in []Risk) []Risk {
	seen := map[string]bool{}
	var out []Risk
	for _, r := range in {
		key := r.Level + r.Reason + r.Source.Path
		if !seen[key] {
			seen[key] = true
			out = append(out, r)
		}
	}
	return out
}

func splitList(raw string) []string {
	raw = strings.Trim(raw, "[]")
	raw = strings.NewReplacer("\"", "", "'", "", "\n", ",", ";", ",", "|", ",").Replace(raw)
	var out []string
	seen := map[string]bool{}
	for _, part := range strings.Split(raw, ",") {
		part = strings.TrimSpace(part)
		if part == "" || seen[part] {
			continue
		}
		seen[part] = true
		out = append(out, part)
	}
	return out
}

func stripJSONComments(s string) string {
	reLine := regexp.MustCompile(`(?m)//.*$`)
	s = reLine.ReplaceAllString(s, "")
	reBlock := regexp.MustCompile(`(?s)/\*.*?\*/`)
	return reBlock.ReplaceAllString(s, "")
}

func anyMap(v any) (map[string]any, bool) {
	m, ok := v.(map[string]any)
	return m, ok
}
func strAny(v any) string {
	if s, ok := v.(string); ok {
		return s
	}
	return ""
}
func strMap(m map[string]any, key string) string { return strAny(firstAnyMap(m, key)) }
func firstAnyMap(m map[string]any, keys ...string) any {
	for _, k := range keys {
		if v, ok := m[k]; ok {
			return v
		}
		for kk, v := range m {
			if strings.EqualFold(kk, k) {
				return v
			}
		}
	}
	return nil
}
func anyStringSlice(v any) []string {
	var out []string
	switch x := v.(type) {
	case []any:
		for _, it := range x {
			if s := strAny(it); s != "" {
				out = append(out, s)
			}
		}
	case []string:
		out = append(out, x...)
	case string:
		out = splitList(x)
	case map[string]any:
		for k := range x {
			out = append(out, k)
		}
	}
	sort.Strings(out)
	return out
}
func anyStringMap(v any) map[string]string {
	out := map[string]string{}
	if m, ok := v.(map[string]any); ok {
		for k, val := range m {
			if s := strAny(val); s != "" {
				out[k] = s
			}
		}
	}
	if len(out) == 0 {
		return nil
	}
	return out
}
func trimEnvRef(s string) string {
	s = strings.TrimSpace(s)
	orig := s
	s = strings.TrimPrefix(s, "$")
	s = strings.TrimPrefix(s, "env:")
	s = strings.TrimPrefix(s, "{env:")
	s = strings.TrimSuffix(s, "}")
	if s == "" {
		return orig
	}
	return s
}
func dedupeProviders(in []ProviderRef) []ProviderRef {
	seen := map[string]bool{}
	var out []ProviderRef
	for _, p := range in {
		if p.Name == "" || p.BaseURL == "" {
			continue
		}
		key := p.Name + "|" + p.BaseURL
		if seen[key] {
			continue
		}
		seen[key] = true
		out = append(out, p)
	}
	return out
}
func pluginRuntime(path string) string {
	low := strings.ToLower(path)
	switch {
	case strings.HasSuffix(low, ".ts") || strings.HasSuffix(low, ".js") || strings.HasSuffix(low, ".mjs"):
		return "node"
	case strings.HasSuffix(low, ".py"):
		return "python"
	case strings.HasSuffix(low, ".sh"):
		return "shell"
	default:
		return "external"
	}
}
