package learn

import (
	"os/exec"
	"regexp"
	"strings"
	"time"
)

// OutcomeDetector determines task result from execution data.
type OutcomeDetector struct{}

// NewOutcomeDetector creates detector.
func NewOutcomeDetector() *OutcomeDetector {
	return &OutcomeDetector{}
}

// Detect determines outcome from execution result.
func (od *OutcomeDetector) Detect(stdout, stderr string, err error, duration time.Duration) Outcome {
	out := Outcome{
		Outcome: "unknown",
	}

	// Check error
	if err != nil {
		out.Outcome = "failed"
		out.Reason = err.Error()
		return out
	}

	// Parse stderr for compilation errors
	if stderr != "" {
		if regexp.MustCompile(`(?i)error|failed|panic|fatal`).MatchString(stderr) {
			out.Outcome = "failed"
			out.Reason = "compilation or runtime error"
			out.CompilationSuccess = false
			return out
		}
	}

	// Default to success if no error
	out.Outcome = "success"
	out.Reason = "completed without error"
	out.CompilationSuccess = true

	// Test result detection (heuristic: look for "PASS", "FAIL")
	if strings.Contains(stdout, "PASS") || strings.Contains(stdout, "ok") {
		out.TestRunSuccess = true
		out.TestPassRate = 1.0
	} else if strings.Contains(stdout, "FAIL") {
		out.TestRunSuccess = false
		out.TestPassRate = 0.0
	}

	// Git commit detection: check if commit within 5min of generation
	// This is approximate; real implementation would hook into git events
	_ = time.Since(time.Now().Add(-5 * time.Minute)) // placeholder

	// User edit detection: compare file mtime
	// Real implementation: monitor file system events or compare timestamps

	return out
}

// AutoScore computes quality score from outcome automatically (0-1).
func AutoScore(outcome Outcome, duration time.Duration) float64 {
	score := 0.5 // baseline

	// Success boosts score
	if outcome.Outcome == "success" {
		score += 0.3
	} else {
		score -= 0.3
	}

	// Latency bonus (fast <2s)
	if duration.Milliseconds() < 2000 {
		score += 0.1
	} else if duration.Milliseconds() > 10000 {
		score -= 0.05
	}

	// Clamp
	if score < 0 {
		score = 0
	} else if score > 1 {
		score = 1
	}

	return score
}

// Quality represents combined quality scoring.
type Quality struct {
	Auto     float64 // 0-1 from heuristics
	User     float64 // 1-10 from explicit feedback (0 if none)
	Combined float64 // weighted avg 1-10
	Final    float64 // final 1-10 score
}

// CombineQuality merges auto and user scores.
func CombineQuality(auto float64, user float64, autoWeight, userWeight float64) float64 {
	if user <= 0 {
		return auto * 10.0 // Convert to 1-10 scale
	}
	combined := auto*autoWeight + user*userWeight
	// Ensure 1-10 range
	if combined < 1 {
		combined = 1
	} else if combined > 10 {
		combined = 10
	}
	return combined
}

// ComputeFinal computes final quality including implicit signals.
func ComputeFinal(baseQuality float64, outcome Outcome) float64 {
	q := baseQuality

	// Compilation success bonus
	if outcome.CompilationSuccess {
		q += 0.5
	} else {
		q -= 1.0
	}

	// Test pass bonus
	if outcome.TestPassRate > 0 {
		q += outcome.TestPassRate * 0.5
	}

	// Git commit bonus (user trusted output)
	if outcome.GitCommitted {
		q += 0.5
	}

	// User edit penalty (needed manual intervention)
	if outcome.UserEdited {
		q -= 0.5
	}

	// Clamp to 1-10
	if q < 1 {
		q = 1
	} else if q > 10 {
		q = 10
	}

	return q
}

// DetectGitCommit checks if user committed code generated by OpenCode.
// Simple heuristic: recent commit mentions "OpenCode" or "Generated".
func DetectGitCommit() bool {
	// Run: git log -1 --format=%s %s (last 5 min)
	cmd := exec.Command("git", "log", "-1", "--format=%s", "--since=5.minutes")
	output, err := cmd.Output()
	if err != nil {
		return false
	}
	msg := strings.ToLower(string(output))
	return strings.Contains(msg, "opencode") || strings.Contains(msg, "generated") || strings.Contains(msg, "ai")
}
