package convert

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
)

type GoGenOptions struct {
	OutDir     string
	Package    string
	Module     string
	Kind       string
	WithTests  bool
	SDKImport  string
	Standalone bool
}

type GeneratedFile struct {
	Path    string
	Content []byte
}

func GenerateGoProject(ir *IR, opts GoGenOptions) ([]GeneratedFile, error) {
	if ir == nil {
		return nil, fmt.Errorf("nil IR")
	}
	pkg := slugGo(opts.Package)
	if pkg == "" {
		pkg = slugGo(ir.Name)
	}
	if pkg == "" {
		pkg = "generatedplugin"
	}
	kind := normalizeName(opts.Kind)
	if kind == "" || kind == "item" {
		kind = ir.Learning.RecommendedKind
	}
	if kind == "" {
		kind = ir.Kind
	}
	module := strings.TrimSpace(opts.Module)
	if module == "" {
		module = "ti.local/generated/" + pkg
	}
	standalone := opts.Standalone || opts.SDKImport == ""
	if opts.SDKImport == "" {
		opts.SDKImport = "github.com/ti/pluginapi"
	}

	irJSON, _ := json.MarshalIndent(ir, "", "  ")
	files := []GeneratedFile{
		{Path: "ir.json", Content: append(irJSON, '\n')},
		{Path: "README.md", Content: []byte(renderGeneratedREADME(ir, kind, standalone))},
	}
	if standalone {
		files = append(files, GeneratedFile{Path: "go.mod", Content: []byte("module " + module + "\n\ngo 1.23\n")})
		mainGo, err := executeTemplate("main.go", standaloneMainTemplate, map[string]any{"Package": "main", "IR": string(irJSON), "Name": ir.Name, "Kind": kind})
		if err != nil {
			return nil, err
		}
		mainGo, _ = format.Source(mainGo)
		files = append(files, GeneratedFile{Path: "main.go", Content: mainGo})
	} else {
		pluginGo, err := executeTemplate("plugin.go", builtInPluginTemplate, map[string]any{"Package": pkg, "IR": string(irJSON), "Name": ir.Name, "Kind": kind, "SDKImport": opts.SDKImport})
		if err != nil {
			return nil, err
		}
		pluginGo, _ = format.Source(pluginGo)
		files = append(files, GeneratedFile{Path: "plugin.go", Content: pluginGo})
	}
	if opts.WithTests {
		testGo, err := executeTemplate("plugin_test.go", generatedTestTemplate, map[string]any{"Package": map[bool]string{true: "main", false: pkg}[standalone], "Standalone": standalone})
		if err != nil {
			return nil, err
		}
		testGo, _ = format.Source(testGo)
		files = append(files, GeneratedFile{Path: "plugin_generated_test.go", Content: testGo})
	}
	return files, nil
}

func WriteGoProject(ir *IR, opts GoGenOptions) ([]GeneratedFile, error) {
	if strings.TrimSpace(opts.OutDir) == "" {
		return nil, fmt.Errorf("missing output directory")
	}
	files, err := GenerateGoProject(ir, opts)
	if err != nil {
		return nil, err
	}
	for _, file := range files {
		path := filepath.Join(opts.OutDir, filepath.FromSlash(file.Path))
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			return nil, err
		}
		if err := os.WriteFile(path, file.Content, 0644); err != nil {
			return nil, err
		}
	}
	return files, nil
}

func executeTemplate(name, body string, data any) ([]byte, error) {
	t, err := template.New(name).Parse(body)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	if err := t.Execute(&b, data); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

func slugGo(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	re := regexp.MustCompile(`[^a-z0-9]+`)
	s = re.ReplaceAllString(s, "_")
	s = strings.Trim(s, "_")
	if s == "" {
		return ""
	}
	if s[0] >= '0' && s[0] <= '9' {
		s = "p_" + s
	}
	return s
}

func renderGeneratedREADME(ir *IR, kind string, standalone bool) string {
	mode := "built-in plugin package"
	if standalone {
		mode = "external standalone plugin binary"
	}
	return fmt.Sprintf(`# %s

Generated by Ti Convert-to-Go.

- IR: %s
- Kind: %s
- Source: %s
- Mode: %s
- Recommended model role: %s
- Risk score: %d

## Build

%s

## Notes

This generated project embeds ir.json as the durable contract. Ti can learn from build/test results and write conversion records into .ti/memory/convert.
`, ir.Name, ir.ID, kind, ir.Source.Format, mode, ir.Learning.RecommendedModel, ir.Learning.RiskScore, buildHint(standalone))
}

func buildHint(standalone bool) string {
	if standalone {
		return "```powershell\ngo test ./...\ngo build .\n```"
	}
	return "```powershell\n# run from the parent Ti CLI module\ngo test ./...\n```"
}

const standaloneMainTemplate = `package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
)

var embeddedIR = []byte({{printf "%q" .IR}})

func main() {
	manifest := flag.Bool("manifest", false, "print generated plugin manifest")
	ir := flag.Bool("ir", false, "print embedded Ti IR")
	run := flag.String("run", "", "run capability by name")
	input := flag.String("input", "", "input text for run")
	flag.Parse()

	if *ir {
		fmt.Println(string(embeddedIR))
		return
	}
	var doc map[string]any
	_ = json.Unmarshal(embeddedIR, &doc)
	if *manifest || *run == "" {
		out, _ := json.MarshalIndent(map[string]any{
			"name": doc["name"],
			"id": doc["id"],
			"kind": {{printf "%q" .Kind}},
			"commands": doc["commands"],
			"tools": doc["tools"],
			"workflows": doc["workflows"],
			"policies": doc["policies"],
		}, "", "  ")
		fmt.Println(string(out))
		return
	}
	fmt.Fprintf(os.Stdout, "generated plugin %s received run=%s input=%s\n", doc["name"], *run, *input)
}
`

const builtInPluginTemplate = `package {{.Package}}

import (
	"context"
	"encoding/json"
	"fmt"

	"{{.SDKImport}}"
)

var embeddedIR = []byte({{printf "%q" .IR}})

func Register(r pluginapi.Registrar) error {
	var ir struct {
		Name string ` + "`json:\"name\"`" + `
		Commands []struct { Name string ` + "`json:\"name\"`" + `; Description string ` + "`json:\"description\"`" + ` } ` + "`json:\"commands\"`" + `
	}
	if err := json.Unmarshal(embeddedIR, &ir); err != nil { return err }
	for _, c := range ir.Commands {
		name := c.Name
		desc := c.Description
		r.Capability(pluginapi.Capability{
			ID: "generated." + name,
			Kind: pluginapi.KindCommand,
			Name: name,
			Description: desc,
			Handler: pluginapi.HandlerFunc(func(ctx context.Context, req pluginapi.Request) (pluginapi.Result, error) {
				return pluginapi.Result{Text: fmt.Sprintf("generated capability %s executed", name)}, nil
			}),
		})
	}
	return nil
}
`

const generatedTestTemplate = `package {{.Package}}

import "testing"

func TestGeneratedPluginEmbedsIR(t *testing.T) {
	if len(embeddedIR) == 0 {
		t.Fatal("embedded IR is empty")
	}
}
`
