package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/ti/cli/internal/packmgr"
)

var (
	packRoot string
	packJSON bool
)

var packCmd = &cobra.Command{
	Use:   "pack",
	Short: "Manage translated Ti packs",
	Long:  "Manage Ti packs generated by translate/provider/plugin compatibility workflows.",
}

var packListCmd = &cobra.Command{
	Use:   "list",
	Short: "List Ti packs",
	RunE: func(cmd *cobra.Command, args []string) error {
		items, err := packmgr.List(packRoot)
		if err != nil {
			return err
		}
		if packJSON {
			fmt.Println(packmgr.JSON(items))
			return nil
		}
		if len(items) == 0 {
			fmt.Println("No packs found. Run `ti translate convert . --out .ti/packs/imported` first.")
			return nil
		}
		fmt.Print(packmgr.RenderList(items))
		return nil
	},
}

var packShowCmd = &cobra.Command{
	Use:   "show <pack-dir-or-ti.pack.yaml>",
	Short: "Inspect a Ti pack",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		info, err := packmgr.Inspect(args[0])
		if err != nil {
			return err
		}
		if packJSON {
			fmt.Println(packmgr.JSON(info))
			return nil
		}
		fmt.Printf("name:      %s\n", info.Name)
		fmt.Printf("path:      %s\n", info.Path)
		fmt.Printf("enabled:   %v\n", info.Enabled)
		fmt.Printf("modified:  %s\n", info.Modified.Format("2006-01-02 15:04:05"))
		fmt.Printf("commands:  %d\n", info.Summary.Commands)
		fmt.Printf("agents:    %d\n", info.Summary.Agents)
		fmt.Printf("skills:    %d\n", info.Summary.Skills)
		fmt.Printf("mcp:       %d\n", info.Summary.MCPServers)
		fmt.Printf("risks:     %d\n", info.Summary.Risks)
		return nil
	},
}

var packEnableCmd = &cobra.Command{
	Use:   "enable <pack-dir>",
	Short: "Enable a Ti pack",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		if err := packmgr.Enable(args[0], true); err != nil {
			return err
		}
		fmt.Printf("enabled: %s\n", args[0])
		return nil
	},
}

var packDisableCmd = &cobra.Command{
	Use:   "disable <pack-dir>",
	Short: "Disable a Ti pack without deleting it",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		if err := packmgr.Enable(args[0], false); err != nil {
			return err
		}
		fmt.Printf("disabled: %s\n", args[0])
		return nil
	},
}

func init() {
	packCmd.PersistentFlags().StringVar(&packRoot, "root", ".ti/packs", "pack root to scan")
	packCmd.PersistentFlags().BoolVar(&packJSON, "json", false, "print JSON output")
	packCmd.AddCommand(packListCmd, packShowCmd, packEnableCmd, packDisableCmd)
	rootCmd.AddCommand(packCmd)
}
